name: Build driver solution
on: [ push ]
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]
    runs-on: windows-2025
    env:
      Solution_Path: ts_litex_driver.sln
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3
        with:
          msbuild-architecture: x64

      - name: Install Packages
        run: |
          msbuild ${{ env.Solution_Path }} -t:build -restore -p:RestorePackagesConfig=true /p:Platform=${{ env.Platform }}
        env:
          Platform: ${{ matrix.platform }}

      - name: Build solution
        run: |
          $COMMIT_DATE = git show -s --format=%cd --date=format:%m/%d/%Y
          $COMMIT_TIMESTAMP = (git show -s --format=%ci).Split(" ")[1]
          $COMMIT_VERSION = $COMMIT_TIMESTAMP -replace ":", "."
          msbuild ${{ env.Solution_Path }} /p:Configuration=${{ env.Configuration }} /p:Platform=${{ env.Platform }} /p:DriverDate=$COMMIT_DATE /p:DriverVersion=$COMMIT_VERSION
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
      
      - name: Upload Driver
        uses: actions/upload-artifact@v4
        with:
          name: thunderscopedrv_${{matrix.configuration}}_${{matrix.platform}}
          path: ${{matrix.platform}}/${{matrix.configuration}}/*
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
